import {
	Sidebar,
	SidebarContent,
	SidebarGroup,
	SidebarGroupContent,
	SidebarGroupTitle,
	SidebarHeader,
	SidebarMenu,
	SidebarMenuItem,
	SidebarMenuLink,
} from '../ui/sidebar';
import { Logo } from './logo';

export const AppSidebar = () => {
	return (
		<Sidebar rail>
			<SidebarHeader className="flex items-center px-6">
				<Logo className="-mb-1.5 h-7" />
			</SidebarHeader>
			<SidebarContent>
				<SidebarGroup>
					<SidebarMenu>
						<SidebarMenuItem>
							<SidebarMenuLink
								href="admin.dashboard"
								icon="hgi-dashboard-square-02"
								tooltip="Dashboard"
							>
								Dashboard
							</SidebarMenuLink>
						</SidebarMenuItem>
					</SidebarMenu>
				</SidebarGroup>
				<SidebarGroup>
					<SidebarGroupTitle>Resources</SidebarGroupTitle>
					<SidebarGroupContent>
						<SidebarMenu>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.authors.index"
									icon="hgi-quill-write-01"
									tooltip="Authors"
								>
									Authors
								</SidebarMenuLink>
							</SidebarMenuItem>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.books.index"
									icon="hgi-book-02"
									tooltip="Books"
								>
									Books
								</SidebarMenuLink>
							</SidebarMenuItem>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.series.index"
									icon="hgi-library"
									tooltip="Series"
								>
									Series
								</SidebarMenuLink>
							</SidebarMenuItem>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.genres.index"
									icon="hgi-tag-02"
									tooltip="Genres"
								>
									Genres
								</SidebarMenuLink>
							</SidebarMenuItem>
						</SidebarMenu>
					</SidebarGroupContent>
				</SidebarGroup>
				<SidebarGroup>
					<SidebarGroupTitle>Controls</SidebarGroupTitle>
					<SidebarGroupContent>
						<SidebarMenu>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.users"
									icon="hgi-user-group"
									tooltip="Users"
								>
									Users
								</SidebarMenuLink>
							</SidebarMenuItem>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.admins"
									icon="hgi-shield-user"
									tooltip="Admins"
								>
									Admins
								</SidebarMenuLink>
							</SidebarMenuItem>
							<SidebarMenuItem>
								<SidebarMenuLink
									href="admin.settings"
									icon="hgi-settings-02"
									tooltip="Settings"
								>
									Settings
								</SidebarMenuLink>
							</SidebarMenuItem>
						</SidebarMenu>
					</SidebarGroupContent>
				</SidebarGroup>
			</SidebarContent>
		</Sidebar>
	);
};
